services:
  - type: worker
    name: aiconsultant-pronpd-bot
    env: python
    region: frankfurt
    plan: free
    buildCommand: "pip install -r requirements.txt && python generate_embeddings.py"
    startCommand: "python bot.py"
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.7
